name: Deploy AWS EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USERNAME  }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            rm -rf /home/ubuntu/<your-repo-name>
            git clone <your-repo-link>.git
            cd <your-repo>
            git checkout master
            git pull origin master
            sudo chmod +x ./deploy.sh
            ./deploy.sh
          '
          rm -rf private_key.pem
